name: Build

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  build:
    runs-on: go-builder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          GIT_SSL_NO_VERIFY: "true"

      - name: Build and test
        shell: bash
        run: |
          set -eu
          go version

          echo "Downloading dependencies..."
          go mod download

          echo "Building..."
          go build -v ./...

          echo "Running tests..."
          go test -v ./...
